//
//  ExtQuote.h
//  StockPicker
//
//  Created by Jason McAnally on 7/12/15.
//  Copyright (c) 2015 Jason McAnally. All rights reserved.
//



#ifndef __StockPicker__ExtQuote__
#define __StockPicker__ExtQuote__

#include <stdio.h>
#include <string>
#include <vector>


class Stock;
class Quote;
class Date;

const std::string _AfterHoursChangeRealtime = "c8",
            _AnnualizedGain = "g3",
            _Ask = "a0",
            _AskRealtime = "b2",
            _AskSize = "a5",
            _AverageDailyVolume = "a2",
            _Bid = "b0",
            _BidRealtime = "b3",
            _BidSize = "b6",
            _BookValuePerShare = "b4",
            _Change = "c1",
            _Change_ChangeInPercent = "c0",
            _ChangeFromFiftydayMovingAverage = "m7",
            _ChangeFromTwoHundreddayMovingAverage = "m5",
            _ChangeFromYearHigh = "k4",
            _ChangeFromYearLow = "j5",
            _ChangeInPercent = "p2",
            _ChangeInPercentRealtime = "k2",
            _ChangeRealtime = "c6",
            _Commission = "c3",
            _Currency = "c4",
            _DaysHigh = "h0",
            _DaysLow = "g0",
            _DaysRange = "m0",
            _DaysRangeRealtime = "w4",
            _DividendPayDate = "r1",
            _TrailingAnnualDividendYield = "d0",
            _TrailingAnnualDividendYieldInPercent = "y0",
            _DilutedEPS = "e0",
            _EBITDA = "j4",
            _EPSEstimateCurrentYear = "e7",
            _EPSEstimateNextQuarter = "e9",
            _EPSEstimateNextYear = "e8",
            _ExDividendDate = "q0",
            _FiftydayMovingAverage = "m3",
            _SharesFloat = "f6",
            _HighLimit = "l2",
            _HoldingsGain = "g4",
            _HoldingsGainPercent = "g1",
            _HoldingsGainPercentRealtime = "g5",
            _HoldingsGainRealtime = "g6",
            _HoldingsValue = "v1",
            _HoldingsValueRealtime = "v7",
            _LastTradeDate = "d1",
            _LastTradePriceOnly = "l1",
            _LastTradeSize = "k3",
            _LastTradeTime = "t1",
            _LastTradeWithTime = "l0",
            _LowLimit = "l3",
            _MarketCapitalization = "j1",
            _MarketCapRealtime = "j3",
            _Name = "n0",
            _Notes = "n4",
            _OneyrTargetPrice = "t8",
            _Open = "o0",
            _OrderBookRealtime = "i5",
            _PEGRatio = "r0",
            _PERatio = "r0",
            _PERatioRealtime = "r2",
            _PercentChangeFromFiftydayMovingAverage = "m8",
            _PercentChangeFromTwoHundreddayMovingAverage = "m6",
            _ChangeInPercentFromYearHigh = "k5",
            _PercentChangeFromYearLow = "j6",
            _PreviousClose = "p0",
            _PriceBook = "p6",
            _PriceEPSEstimateCurrentYear = "r6",
            _PriceEPSEstimateNextYear = "r7",
            _PricePaid = "p1",
            _PriceSales = "p5",
            _Revenue = "s6",
            _SharesOwned = "s1",
            _SharesOutstanding = "j2",
            _ShortRatio = "s7",
            _StockExchange = "x0",
            _Symbol = "s0",
            _TickerTrend = "t7",
            _TradeData = "d2",
            _TradeLinks = "t6",
            _TradeLinksAdditional = "f0",
            _TwoHundreddayMovingAverage = "m4",
            _Volume = "v0",
            _YearHigh = "k0",
            _YearLow = "j0",
            _YearRange = "w0";


class ExtQuote {
public:
    double afterHoursChangeRealtime,
            annualizedGain,
            ask,
            askRealtime,
            askSize,
            averageDailyVolume,
            bid,
            bidRealtime,
            bidSize,
            bookValuePerShare,
            change,
            change_ChangeInPercent,
            changeFromFiftydayMovingAverage,
            changeFromTwoHundreddayMovingAverage,
            changeFromYearHigh,
            changeFromYearLow,
            changeInPercent,
            changeInPercentRealtime,
            changeRealtime,
            commission,
            daysHigh,
            daysLow,
            daysRange,
            daysRangeRealtime,
            trailingAnnualDividendYield,
            trailingAnnualDividendYieldInPercent,
            dilutedEPS,
            eBITDA,
            ePSEstimateCurrentYear,
            ePSEstimateNextQuarter,
            ePSEstimateNextYear,
            fiftydayMovingAverage,
            highLimit,
            holdingsGain,
            holdingsGainPercent,
            holdingsGainPercentRealtime,
            holdingsGainRealtime,
            holdingsValue,
            holdingsValueRealtime,
            lastTradePriceOnly,
            lastTradeSize,
            lastTradeTime,
            lowLimit,
            marketCapitalization,
            marketCapRealtime,
            oneyrTargetPrice,
            open,
            orderBookRealtime,
            pEGRatio,
            pERatio,
            pERatioRealtime,
            percentChangeFromFiftydayMovingAverage,
            percentChangeFromTwoHundreddayMovingAverage,
            changeInPercentFromYearHigh,
            percentChangeFromYearLow,
            previousClose,
            priceBook,
            priceEPSEstimateCurrentYear,
            priceEPSEstimateNextYear,
            pricePaid,
            priceSales,
            revenue,
            shortRatio,
            twoHundreddayMovingAverage,
            yearHigh,
            yearLow,
            yearRange;
    
    std::string currency,
            name,
            notes,
            stockExchange,
            symbol,
            tickerTrend,
            tradeData,
            tradeLinks,
            tradeLinksAdditional;
    
    Date* dividendPayDate,
            * exDividendDate,
            * lastTradeDate;
    
    long sharesOwned,
            sharesOutstanding,
            volume;

    ExtQuote();
    
    ExtQuote(Stock* stock, std::vector<std::string>& s);

    ExtQuote(
             double pAfterHoursChangeRealtime,
             double pAnnualizedGain,
             double pAsk,
             double pAskRealtime,
             double pAskSize,
             double pAverageDailyVolume,
             double pBid,
             double pBidRealtime,
             double pBidSize,
             double pBookValuePerShare,
             double pChange,
             double pChange_ChangeInPercent,
             double pChangeFromFiftydayMovingAverage,
             double pChangeFromTwoHundreddayMovingAverage,
             double pChangeFromYearHigh,
             double pChangeFromYearLow,
             double pChangeInPercent,
             double pChangeInPercentRealtime,
             double pChangeRealtime,
             double pCommission,
             double pDaysHigh,
             double pDaysLow,
             double pDaysRange,
             double pDaysRangeRealtime,
             double pTrailingAnnualDividendYield,
             double pTrailingAnnualDividendYieldInPercent,
             double pDilutedEPS,
             double pEBITDA,
             double pEPSEstimateCurrentYear,
             double pEPSEstimateNextQuarter,
             double pEPSEstimateNextYear,
             double pFiftydayMovingAverage,
             double pHighLimit,
             double pHoldingsGain,
             double pHoldingsGainPercent,
             double pHoldingsGainPercentRealtime,
             double pHoldingsGainRealtime,
             double pHoldingsValue,
             double pHoldingsValueRealtime,
             double pLastTradePriceOnly,
             double pLastTradeSize,
             double pLastTradeTime,
             double pLowLimit,
             double pMarketCapitalization,
             double pMarketCapRealtime,
             double pOneyrTargetPrice,
             double pOpen,
             double pOrderBookRealtime,
             double pPEGRatio,
             double pPERatio,
             double pPERatioRealtime,
             double pPercentChangeFromFiftydayMovingAverage,
             double pPercentChangeFromTwoHundreddayMovingAverage,
             double pChangeInPercentFromYearHigh,
             double pPercentChangeFromYearLow,
             double pPreviousClose,
             double pPriceBook,
             double pPriceEPSEstimateCurrentYear,
             double pPriceEPSEstimateNextYear,
             double pPricePaid,
             double pPriceSales,
             double pRevenue,
             double pShortRatio,
             double pTwoHundreddayMovingAverage,
             double pYearHigh,
             double pYearLow,
             double pYearRange,
             std::string pCurrency,
             std::string pName,
             std::string pNotes,
             std::string pStockExchange,
             std::string pSymbol,
             std::string pTickerTrend,
             std::string pTradeData,
             std::string pTradeLinks,
             std::string pTradeLinksAdditional,
             Date* pDividendPayDate,
             Date* pExDividendDate,
             Date* pLastTradeDate,
             long pSharesOwned,
             long pSharesOutstanding,
             long pVolume
             );
    
    
};


#endif /* defined(__StockPicker__ExtQuote__) */
